AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyDataBase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: postgres
      DBInstanceClass: db.t3.micro
      MasterUsername: fer
      MasterUserPassword: opiqwenxchdf9474823
      AllocatedStorage: 20

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0aa7d40eeae50c9a9
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"

