AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SNS Basic
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      PackageType: Zip
      InlineCode: |
        import json
        def handler(event, context):
          event = json.loads(event['Records'][0]['Sns']['Message'])
          print('event', event)
          message = 'Hello {} {}!'.format(event['first_name'], event['last_name'])
          print("Log this for me")
          return {
            'message': message,
          }
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic
