AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Recipes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: Category
          KeyType: HASH
        - AttributeName: Title
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: Category
          AttributeType: S
        - AttributeName: Title
          AttributeType: S
