AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MySecretGenerated:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
  MySecretProvided:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      SecretString: 'top secret'
